// 本文件为生成的代码，所有修改都会丢失
using System;
using System.Collections.Generic;
public class ProtoMeta : IProtoMeta
{
    public uint GetMsgId(Type msgType)
    {
        return typeToMsgId[msgType];
    }

    public readonly Dictionary<Type, uint> typeToMsgId = new()
    {
        {typeof(Ping), ProtoMsgId.Ping},
        {typeof(Pong), ProtoMsgId.Pong},
        {typeof(Result), ProtoMsgId.Result},
        {typeof(NPlayer), ProtoMsgId.NPlayer},
        {typeof(NOtherPlayer), ProtoMsgId.NOtherPlayer},
        {typeof(NMaterialItem), ProtoMsgId.NMaterialItem},
        {typeof(NCurrencyItem), ProtoMsgId.NCurrencyItem},
        {typeof(NWeaponItem), ProtoMsgId.NWeaponItem},
        {typeof(NDiscItem), ProtoMsgId.NDiscItem},
        {typeof(NFloat3), ProtoMsgId.NFloat3},
        {typeof(NPosRot), ProtoMsgId.NPosRot},
        {typeof(NWeaponAttr), ProtoMsgId.NWeaponAttr},
        {typeof(NDiscAttr), ProtoMsgId.NDiscAttr},
        {typeof(MsgGachaWeapon), ProtoMsgId.MsgGachaWeapon},
        {typeof(MsgGachaDisc), ProtoMsgId.MsgGachaDisc},
        {typeof(ReqRegister), ProtoMsgId.ReqRegister},
        {typeof(RspRegister), ProtoMsgId.RspRegister},
        {typeof(ReqLogin), ProtoMsgId.ReqLogin},
        {typeof(RspLogin), ProtoMsgId.RspLogin},
        {typeof(ReqGetPlayerInfo), ProtoMsgId.ReqGetPlayerInfo},
        {typeof(RspGetPlayerInfo), ProtoMsgId.RspGetPlayerInfo},
        {typeof(NRoomSimPlayerInfo), ProtoMsgId.NRoomSimPlayerInfo},
        {typeof(MsgEnterRoom), ProtoMsgId.MsgEnterRoom},
        {typeof(MsgUpdateSelf), ProtoMsgId.MsgUpdateSelf},
        {typeof(NotifyUpdateSelf), ProtoMsgId.NotifyUpdateSelf},
        {typeof(NotifyOthersEnterRoom), ProtoMsgId.NotifyOthersEnterRoom},
        {typeof(NotifyOtherLeaveRoom), ProtoMsgId.NotifyOtherLeaveRoom},
        {typeof(NotifyUpdateOther), ProtoMsgId.NotifyUpdateOther},
        {typeof(MsgPlayAction), ProtoMsgId.MsgPlayAction},
        {typeof(NotifyOtherPlayAction), ProtoMsgId.NotifyOtherPlayAction},
        {typeof(MsgSwitchRole), ProtoMsgId.MsgSwitchRole},
        {typeof(NotifySwitchRole), ProtoMsgId.NotifySwitchRole},
        {typeof(ReqGetExchangeItems), ProtoMsgId.ReqGetExchangeItems},
        {typeof(RspGetExchangeItems), ProtoMsgId.RspGetExchangeItems},
        {typeof(NExchangeItem), ProtoMsgId.NExchangeItem},
        {typeof(ReqExchange), ProtoMsgId.ReqExchange},
        {typeof(RspExchange), ProtoMsgId.RspExchange},
        {typeof(ReqSearchPlayer), ProtoMsgId.ReqSearchPlayer},
        {typeof(RspSearchPlayer), ProtoMsgId.RspSearchPlayer},
        {typeof(ReqGetFriendInfos), ProtoMsgId.ReqGetFriendInfos},
        {typeof(RspGetFriendInfos), ProtoMsgId.RspGetFriendInfos},
        {typeof(ReqSendAddFriend), ProtoMsgId.ReqSendAddFriend},
        {typeof(RspSendAddFriend), ProtoMsgId.RspSendAddFriend},
        {typeof(ReqAcceptAddFriend), ProtoMsgId.ReqAcceptAddFriend},
        {typeof(RspAcceptAddFriend), ProtoMsgId.RspAcceptAddFriend},
        {typeof(ReqRefuseAddFriend), ProtoMsgId.ReqRefuseAddFriend},
        {typeof(RspRefuseAddFriend), ProtoMsgId.RspRefuseAddFriend},
        {typeof(ReqDeleteFriend), ProtoMsgId.ReqDeleteFriend},
        {typeof(RspDeleteFriend), ProtoMsgId.RspDeleteFriend},
        {typeof(ReqModifySignature), ProtoMsgId.ReqModifySignature},
        {typeof(RspModifySignature), ProtoMsgId.RspModifySignature},
        {typeof(ReqModifyPassword), ProtoMsgId.ReqModifyPassword},
        {typeof(RspModifyPassword), ProtoMsgId.RspModifyPassword},
        {typeof(ReqModifyAvatar), ProtoMsgId.ReqModifyAvatar},
        {typeof(RspModifyAvatar), ProtoMsgId.RspModifyAvatar},
        {typeof(NChatMsg), ProtoMsgId.NChatMsg},
        {typeof(NChatMsgRecord), ProtoMsgId.NChatMsgRecord},
        {typeof(ReqSendChatMsg), ProtoMsgId.ReqSendChatMsg},
        {typeof(RspSendChatMsg), ProtoMsgId.RspSendChatMsg},
        {typeof(NotifyReceiveChatMsg), ProtoMsgId.NotifyReceiveChatMsg},
        {typeof(ReqGetChatRecords), ProtoMsgId.ReqGetChatRecords},
        {typeof(RspGetChatRecords), ProtoMsgId.RspGetChatRecords},
        {typeof(NRole), ProtoMsgId.NRole},
        {typeof(ReqRoleRemoveDisc), ProtoMsgId.ReqRoleRemoveDisc},
        {typeof(RspRoleRemoveDisc), ProtoMsgId.RspRoleRemoveDisc},
        {typeof(ReqRoleEquipDisc), ProtoMsgId.ReqRoleEquipDisc},
        {typeof(RspRoleEquipDisc), ProtoMsgId.RspRoleEquipDisc},
        {typeof(ReqRoleRemoveWeapon), ProtoMsgId.ReqRoleRemoveWeapon},
        {typeof(RspRoleRemoveWeapon), ProtoMsgId.RspRoleRemoveWeapon},
        {typeof(ReqRoleEquipWeapon), ProtoMsgId.ReqRoleEquipWeapon},
        {typeof(RspRoleEquipWeapon), ProtoMsgId.RspRoleEquipWeapon},
        {typeof(NotifySpawnMonster), ProtoMsgId.NotifySpawnMonster},
        {typeof(MsgMonsterTakeDamage), ProtoMsgId.MsgMonsterTakeDamage},
        {typeof(NotifySyncMonsterTakeDamage), ProtoMsgId.NotifySyncMonsterTakeDamage},
        {typeof(NotifyMonsterDie), ProtoMsgId.NotifyMonsterDie},
        {typeof(ReqStartQuest), ProtoMsgId.ReqStartQuest},
        {typeof(RspStartQuest), ProtoMsgId.RspStartQuest},
        {typeof(ReqUpgradeDisc), ProtoMsgId.ReqUpgradeDisc},
        {typeof(RspUpgradeDisc), ProtoMsgId.RspUpgradeDisc},
        {typeof(MsgGatherMaterial), ProtoMsgId.MsgGatherMaterial},
        {typeof(MsgCompleteQuestChain), ProtoMsgId.MsgCompleteQuestChain},
        {typeof(NotifyObtainItems), ProtoMsgId.NotifyObtainItems},
    };

    public Google.Protobuf.MessageParser GetParser(uint msgId)
    {
        return msgId switch
        {
            ProtoMsgId.Ping => Ping.Parser,
            ProtoMsgId.Pong => Pong.Parser,
            ProtoMsgId.Result => Result.Parser,
            ProtoMsgId.NPlayer => NPlayer.Parser,
            ProtoMsgId.NOtherPlayer => NOtherPlayer.Parser,
            ProtoMsgId.NMaterialItem => NMaterialItem.Parser,
            ProtoMsgId.NCurrencyItem => NCurrencyItem.Parser,
            ProtoMsgId.NWeaponItem => NWeaponItem.Parser,
            ProtoMsgId.NDiscItem => NDiscItem.Parser,
            ProtoMsgId.NFloat3 => NFloat3.Parser,
            ProtoMsgId.NPosRot => NPosRot.Parser,
            ProtoMsgId.NWeaponAttr => NWeaponAttr.Parser,
            ProtoMsgId.NDiscAttr => NDiscAttr.Parser,
            ProtoMsgId.MsgGachaWeapon => MsgGachaWeapon.Parser,
            ProtoMsgId.MsgGachaDisc => MsgGachaDisc.Parser,
            ProtoMsgId.ReqRegister => ReqRegister.Parser,
            ProtoMsgId.RspRegister => RspRegister.Parser,
            ProtoMsgId.ReqLogin => ReqLogin.Parser,
            ProtoMsgId.RspLogin => RspLogin.Parser,
            ProtoMsgId.ReqGetPlayerInfo => ReqGetPlayerInfo.Parser,
            ProtoMsgId.RspGetPlayerInfo => RspGetPlayerInfo.Parser,
            ProtoMsgId.NRoomSimPlayerInfo => NRoomSimPlayerInfo.Parser,
            ProtoMsgId.MsgEnterRoom => MsgEnterRoom.Parser,
            ProtoMsgId.MsgUpdateSelf => MsgUpdateSelf.Parser,
            ProtoMsgId.NotifyUpdateSelf => NotifyUpdateSelf.Parser,
            ProtoMsgId.NotifyOthersEnterRoom => NotifyOthersEnterRoom.Parser,
            ProtoMsgId.NotifyOtherLeaveRoom => NotifyOtherLeaveRoom.Parser,
            ProtoMsgId.NotifyUpdateOther => NotifyUpdateOther.Parser,
            ProtoMsgId.MsgPlayAction => MsgPlayAction.Parser,
            ProtoMsgId.NotifyOtherPlayAction => NotifyOtherPlayAction.Parser,
            ProtoMsgId.MsgSwitchRole => MsgSwitchRole.Parser,
            ProtoMsgId.NotifySwitchRole => NotifySwitchRole.Parser,
            ProtoMsgId.ReqGetExchangeItems => ReqGetExchangeItems.Parser,
            ProtoMsgId.RspGetExchangeItems => RspGetExchangeItems.Parser,
            ProtoMsgId.NExchangeItem => NExchangeItem.Parser,
            ProtoMsgId.ReqExchange => ReqExchange.Parser,
            ProtoMsgId.RspExchange => RspExchange.Parser,
            ProtoMsgId.ReqSearchPlayer => ReqSearchPlayer.Parser,
            ProtoMsgId.RspSearchPlayer => RspSearchPlayer.Parser,
            ProtoMsgId.ReqGetFriendInfos => ReqGetFriendInfos.Parser,
            ProtoMsgId.RspGetFriendInfos => RspGetFriendInfos.Parser,
            ProtoMsgId.ReqSendAddFriend => ReqSendAddFriend.Parser,
            ProtoMsgId.RspSendAddFriend => RspSendAddFriend.Parser,
            ProtoMsgId.ReqAcceptAddFriend => ReqAcceptAddFriend.Parser,
            ProtoMsgId.RspAcceptAddFriend => RspAcceptAddFriend.Parser,
            ProtoMsgId.ReqRefuseAddFriend => ReqRefuseAddFriend.Parser,
            ProtoMsgId.RspRefuseAddFriend => RspRefuseAddFriend.Parser,
            ProtoMsgId.ReqDeleteFriend => ReqDeleteFriend.Parser,
            ProtoMsgId.RspDeleteFriend => RspDeleteFriend.Parser,
            ProtoMsgId.ReqModifySignature => ReqModifySignature.Parser,
            ProtoMsgId.RspModifySignature => RspModifySignature.Parser,
            ProtoMsgId.ReqModifyPassword => ReqModifyPassword.Parser,
            ProtoMsgId.RspModifyPassword => RspModifyPassword.Parser,
            ProtoMsgId.ReqModifyAvatar => ReqModifyAvatar.Parser,
            ProtoMsgId.RspModifyAvatar => RspModifyAvatar.Parser,
            ProtoMsgId.NChatMsg => NChatMsg.Parser,
            ProtoMsgId.NChatMsgRecord => NChatMsgRecord.Parser,
            ProtoMsgId.ReqSendChatMsg => ReqSendChatMsg.Parser,
            ProtoMsgId.RspSendChatMsg => RspSendChatMsg.Parser,
            ProtoMsgId.NotifyReceiveChatMsg => NotifyReceiveChatMsg.Parser,
            ProtoMsgId.ReqGetChatRecords => ReqGetChatRecords.Parser,
            ProtoMsgId.RspGetChatRecords => RspGetChatRecords.Parser,
            ProtoMsgId.NRole => NRole.Parser,
            ProtoMsgId.ReqRoleRemoveDisc => ReqRoleRemoveDisc.Parser,
            ProtoMsgId.RspRoleRemoveDisc => RspRoleRemoveDisc.Parser,
            ProtoMsgId.ReqRoleEquipDisc => ReqRoleEquipDisc.Parser,
            ProtoMsgId.RspRoleEquipDisc => RspRoleEquipDisc.Parser,
            ProtoMsgId.ReqRoleRemoveWeapon => ReqRoleRemoveWeapon.Parser,
            ProtoMsgId.RspRoleRemoveWeapon => RspRoleRemoveWeapon.Parser,
            ProtoMsgId.ReqRoleEquipWeapon => ReqRoleEquipWeapon.Parser,
            ProtoMsgId.RspRoleEquipWeapon => RspRoleEquipWeapon.Parser,
            ProtoMsgId.NotifySpawnMonster => NotifySpawnMonster.Parser,
            ProtoMsgId.MsgMonsterTakeDamage => MsgMonsterTakeDamage.Parser,
            ProtoMsgId.NotifySyncMonsterTakeDamage => NotifySyncMonsterTakeDamage.Parser,
            ProtoMsgId.NotifyMonsterDie => NotifyMonsterDie.Parser,
            ProtoMsgId.ReqStartQuest => ReqStartQuest.Parser,
            ProtoMsgId.RspStartQuest => RspStartQuest.Parser,
            ProtoMsgId.ReqUpgradeDisc => ReqUpgradeDisc.Parser,
            ProtoMsgId.RspUpgradeDisc => RspUpgradeDisc.Parser,
            ProtoMsgId.MsgGatherMaterial => MsgGatherMaterial.Parser,
            ProtoMsgId.MsgCompleteQuestChain => MsgCompleteQuestChain.Parser,
            ProtoMsgId.NotifyObtainItems => NotifyObtainItems.Parser,
            _ => null,
        };
    }

    public bool IsRsp(uint msgId)
    {
        return msgId switch
        {
            ProtoMsgId.Pong => true,
            ProtoMsgId.RspRegister => true,
            ProtoMsgId.RspLogin => true,
            ProtoMsgId.RspGetPlayerInfo => true,
            ProtoMsgId.RspGetExchangeItems => true,
            ProtoMsgId.RspExchange => true,
            ProtoMsgId.RspSearchPlayer => true,
            ProtoMsgId.RspGetFriendInfos => true,
            ProtoMsgId.RspSendAddFriend => true,
            ProtoMsgId.RspAcceptAddFriend => true,
            ProtoMsgId.RspRefuseAddFriend => true,
            ProtoMsgId.RspDeleteFriend => true,
            ProtoMsgId.RspModifySignature => true,
            ProtoMsgId.RspModifyPassword => true,
            ProtoMsgId.RspModifyAvatar => true,
            ProtoMsgId.RspSendChatMsg => true,
            ProtoMsgId.RspGetChatRecords => true,
            ProtoMsgId.RspRoleRemoveDisc => true,
            ProtoMsgId.RspRoleEquipDisc => true,
            ProtoMsgId.RspRoleRemoveWeapon => true,
            ProtoMsgId.RspRoleEquipWeapon => true,
            ProtoMsgId.RspStartQuest => true,
            ProtoMsgId.RspUpgradeDisc => true,
            _ => false,
        };
    }
}
